// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Les commandes Prisma (migrations) passent par DIRECT_URL quand elle est
    // définie : sur Vercel, DATABASE_URL pointe vers le pooler en mode
    // transaction (port 6543), sur lequel les migrations se bloquent.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
